seajs.config({
			alias : {
				'jquery' : 'jquery.js',
				'moment':'demoAssets/../../util/moment.js',
				'validation' : 'demoAssets/../../validation/jquery.validate.customize.js',
				'datepicker' : 'demoAssets/../../datepicker/jquery.ui.datepicker-zh-CN.js',
				'datepickerCN' : 'demoAssets/../../datepicker/jquery.ui.datepicker-zh-CN.js',
				'datepickerEn' : 'demoAssets/../../datepicker/jquery.ui.datepicker-en.js',
				'grid' : 'demoAssets/../../grid/jquery.grid.js',
				'pager' : 'demoAssets/../../pagination/jquery.pagination.js',
				'button' : 'demoAssets/../../core/jquery.ui.button.js',
				'tree' : 'demoAssets/../../tree/jquery.tree.customize.js',
				'dialog' : 'demoAssets/../../dialog/jquery.ui.dialog.customize.js',
				'util' : 'demoAssets/../../util/common-util.js',
				'uriTemplate' : 'demoAssets/../../util/uritemplate.js',
				'block' : 'demoAssets/../../block/jquery.blockUI.customize.js',
				'form' : 'demoAssets/../../form/jquery.form.js',
				'queryString' : 'demoAssets/../../querystring/querystring.js',
				'tabs' : 'demoAssets/../../tabs/jquery.ui.tabs.js',
				'listnav' : 'demoAssets/../../listnav/jquery.listnav.js',
				'autoComplete' : 'demoAssets/../../autocomplete/jquery.ui.autocomplete.js',
				'multiFile' : 'demoAssets/../../file/jquery.MultiFile.js',
				'dateTimePicker' : 'demoAssets/../../datetimepicker/jquery.ui.datetimepicker-zh-CN.js',
				'timepicker':'demoAssets/../../timepicker/jquery.ui.timepicker-zh-CN.js',
				'tip' : 'demoAssets/../../tip/jquery.bt.js',
				'sort' : 'demoAssets/../../dnd/jquery.ui.sortable.js',
				'bgiframe' : 'demoAssets/../../core/jquery.bgiframe.js',
				'template' : 'demoAssets/../../template/jquery.tmpl.js',
				'hoverDelay' : 'demoAssets/../../util/hoverDelay.js',
				'cookie' : 'demoAssets/../../cookie/jquery.cookie.js',
				'zoom' : 'demoAssets/../../zoom/cloud-zoom.js',
				'base64' : 'demoAssets/../../util/jquery.base64.js',
				'metadata' : 'demoAssets/../../metadata/jquery.metadata.js',
				'password' : 'demoAssets/../../password/jquery.passwordStrength.js',
				'jqGrid':'demoAssets/../../jqGrid/grid.locale-cn.js',
				'accordion':'demoAssets/../../accordion/jquery.ui.accordion.js',
				'jqueryCSS' : 'demoAssets/../../style/jquery-ui-1.8.14.custom.css',
				'gridCSS' : 'demoAssets/../../style/grid.css',
				'validationCSS' : 'demoAssets/../../style/validation.css',
				'tipCSS' : 'demoAssets/../../style/jquery.bt.css',
				'zoomCSS' : 'demoAssets/../../style/cloud-zoom.css',
				'timepickerCSS':'demoAssets/../../style/jquery.ui.timepicker.css'
			},
			preload : [ 'jquery', 'plugin-text' ],
			charset : 'UTF-8',
			timeout : 20000,
			debug : false
		});
